/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MenuItem {
  created_at: Timestamp;
  id: Generated<number>;
  image: string | null;
  is_available: Generated<boolean>;
  name: string;
  price: number;
  restaurant_id: number;
}

export interface MikroOrmMigrations {
  executed_at: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string | null;
}

export interface Order {
  created_at: Timestamp;
  customer_id: number;
  delivery_staff_id: number | null;
  estimated_time: number | null;
  id: Generated<number>;
  restaurant_id: number;
  status: Generated<string>;
  total_amount: number;
}

export interface OrderItem {
  id: Generated<number>;
  menu_item_id: number;
  order_id: number;
  price: number;
  quantity: number;
}

export interface Restaurant {
  created_at: Timestamp;
  id: Generated<number>;
  image: string | null;
  name: string;
  owner_id: number;
}

export interface User {
  created_at: Timestamp;
  email: string;
  id: Generated<number>;
  name: string;
  password: string;
  phone: string | null;
  role: string;
}

export interface DB {
  menu_item: MenuItem;
  mikro_orm_migrations: MikroOrmMigrations;
  order: Order;
  order_item: OrderItem;
  restaurant: Restaurant;
  user: User;
}
